eureka:
  client:
    service-url:
      defaultZone: http://172.16.8.151:8761/eureka/ # URL of the Eureka server
  instance:
    prefer-ip-address: true



#docs

springdoc:
  api-docs:
    path: /v3/api-docs
