
eureka:
  client:
    service-url:
<<<<<<< Updated upstream
      #defaultZone: http://172.16.8.151:8761/eureka/ # URL of the Eureka server
      defaultZone: http://localhost:8761/eureka/
=======
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server
>>>>>>> Stashed changes
  instance:
    prefer-ip-address: true


#docs
springdoc:
  api-docs:
    path: /v3/api-docs
