server:
  port: 8083

#eureka:
#  eureka:
#    instance:
#      lease-renewal-interval-in-seconds: 10
#  client:
#  service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    template:
      default-topic: "account-topic"
    producer:
      properties:
        spring.json.type.mapping: AccountEvent:package com.bank.account_service.Event.AccountEvent;
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer"


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/account_service_db
    username: dev_team
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect