# Spring properties
#spring:
#  application:
#    name: school-api-gateway

server:
  port: 8084 # Port for the microservice

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service  # Give it a name
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Auto-detect services in Eureka
          lower-case-service-id: true  # Match service names correctly
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/user

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**
          filters:
            - name: CircuitBreaker
              args:
                name: accountServiceCircuitBreaker
                fallbackUri: forward:/fallback/account

        - id: audit-service
          uri: lb://AUDIT-SERVICE
          predicates:
            - Path=/api/audit_logs/**
          filters:
            - name: CircuitBreaker
              args:
                name: auditLogsServiceCircuitBreaker
                fallbackUri: forward:/fallback/audit

<<<<<<< Updated upstream
eureka:
  client:
    service-url:
      #defaultZone: http://172.16.8.151:8761/eureka/ # URL of the Eureka server
      defaultZone: http://localhost:8761/eureka/
=======
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transactions/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/transaction

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server
>>>>>>> Stashed changes
  instance:
    prefer-ip-address: true # Use IP address instead of hostname

management:

  endpoints:
    web:
      exposure:
        include: "gateway, health, info, metrics"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    version: openapi_3_1
    groups:
      enabled: true
    urls:
      - name: USER-SERVICE
        url: http://user-service/v3/api-docs
      - name: TRANSACTION-SERVICE
        url: http://transaction-service/v3/api-docs
#      - name: Microservice-3
#        url: http://microservice-3/v3/api-docs

